remote_theme: pages-themes/midnight@v0.2.0
plugins:
- jekyll-remote-theme
title: Analyzing the Impacts of Power Outages on California's Economy
description: This is a data science project that aims to investigate the correlation between power outages and fluctuations in a state’s gross state product (GSP) within California. The dataset utilized for this investigation can be accessed via the following source. Our findings are presented in this report, which was completed as part of the DSC80 course at UCSD.
